# Inhoud van bouwpartnerseindhoven.nl. build.py maakt hier de pagina's van.
#
# Uitgangspunt: alleen wat bevestigd is. Geen prijzen, termijnen, garanties,
# certificaten, reviews of jaren ervaring. Foto's beschrijven wat erop te zien is;
# werk dat nog bezig is, heet ook zo.

GROEPEN = {"dak": "Dak & zolder", "tuin": "Tuin & bomen", "aanbouw": "Aanbouw"}

# Vestiging en werkgebied (bevestigd door de klant, 6 okt 2026)
VESTIGING = "Asten"
PLAATSEN = ["Asten", "Someren", "Deurne", "Helmond", "Geldrop", "Eindhoven"]
PLAATSEN_TEKST = "Asten, Someren, Deurne, Helmond, Geldrop en Eindhoven"

# Alle projectfoto's: (alt-tekst, status). Status "uitvoering" = foto gemaakt tijdens het werk.
FOTO = {
    "dakwerk": ("Vakman aan het werk tussen de panlatten op een schuin dak, met de steiger ernaast", "uitvoering"),
    "dak-1": ("Schuin dak in opbouw met dakplaten en panlatten, steiger en kraan", "uitvoering"),
    "dak-2": ("Dakplaten met panlatten liggen klaar terwijl een kraan een dakdeel hijst", "uitvoering"),
    "dak-3": ("Woning in de steigers met een schuin dak in opbouw", "uitvoering"),
    "dak-plat": ("Groot plat dak met dakbedekking in banen", ""),
    "zolder-1": ("Wit afgewerkt schuin plafond met inbouwspots", ""),
    "zolder-2": ("Zolder met gipsplaten tegen de schuine dakvlakken, een dakkapel en twee smalle ramen", "uitvoering"),
    "zolder-3": ("Zolder met beplating rond de opening van een dakkapel", "uitvoering"),
    "zolder-4": ("Ruime zolder met dakkapel, beplating en rolsteiger", "uitvoering"),
    "zolder-5": ("Zolder in opbouw met een vloer van plaatmateriaal en een dakraam", "uitvoering"),
    "zolder-6": ("Nieuwe zoldervloer van balken en plaatmateriaal in aanleg", "uitvoering"),
    "zolder-7": ("Schuine dakvlakken bekleed met plaatmateriaal, met een dakkapel en rolsteiger", "uitvoering"),
    "tuin-1": ("Tuin met gazon, tegelpad, vuurschaal en een overkapping met glazen wanden", ""),
    "tuin-2": ("Terras van gebakken klinkers met borders, tuinverlichting en een houten tuinhuis", ""),
    "tuin-3": ("Tuin met gazon, tegelpad en een verhoogde plantenbak met lavendel", ""),
    "tuin-4": ("Tuin met gazon, tegelterras en een nieuwe houten schutting", ""),
    "tuin-5": ("Pas gelegde graszoden in een ruime tuin, met een overkapping op de achtergrond", ""),
    "tuin-6": ("Tuinpad in aanleg tussen grindstroken, naast een gazon", "uitvoering"),
    "tuin-7": ("Staptegels in wit grind naast een gazon", ""),
    "tuin-8": ("Tuin in aanleg: tegels worden gelegd tussen stroken grind", "uitvoering"),
    "tuin-9": ("Verhoogde plantenbakken met leisteensplit en olijfboompjes in pot", ""),
    "tuin-10": ("Voortuin met wit grind, cortenstalen plantenbakken en keien", ""),
    "tuin-11": ("Zijpad van grote tegels met een afvoergoot langs de gevel", ""),
    "tuin-12": ("Gazon met een sproeier, omringd door hagen", ""),
    "overkapping-1": ("Houten overkapping met plat dak tegen de achtergevel, met zitplek en hangstoel", ""),
    "overkapping-2": ("Houten overkapping over de volle breedte van de achtergevel", ""),
    "overkapping-3": ("Onderkant van een houten overkapping met balken en een plafond van houten delen", ""),
    "overkapping-4": ("Houten achterwand en plafond van een overkapping", ""),
    "overkapping-5": ("Houten plafond en balken van een overkapping tegen de gevel", ""),
    "overkapping-6": ("Houten overkapping met zitplek, terras en kunstgras", ""),
    "overkapping-7": ("Houten staanders van een overkapping naast kunstgras en klinkers", ""),
    "overkapping-8": ("Overkapping in opbouw met wit geschilderde balken tegen de gevel", "uitvoering"),
    "overkapping-9": ("Houten overkapping aan het huis met terras, kunstgras en een hangmat", ""),
}

# ---------------------------------------------------------------------------
# Diensten. Elke pagina heeft een eigen zoekintentie en een eigen opbouw.
# Bloktypen (zie build.py): kaarten, lijst, vergelijk, tekst, info, prijs, combi, vragen, regio
DIENSTEN = [
    dict(slug="dakwerken", groep="dak", nr="01", naam="Dakwerken", oppervlakte="dak",
         kort="Plat of schuin dak, van gericht herstel tot opnieuw opbouwen.",
         titel="Dakwerken in Eindhoven en omgeving | Bouwpartners Eindhoven",
         meta="Versleten dakbedekking, losse pannen of een dak dat opnieuw moet? Bouwpartners Eindhoven uit Asten bekijkt je dak en bespreekt de aanpak. Eindhoven en omgeving.",
         h1="Dakwerken in Eindhoven en omgeving",
         intro="Een plat dak waarvan de bedekking op is, pannen die verschoven zijn of een dak dat helemaal opnieuw moet. We beginnen bij de staat van je dak en bespreken daarna welke aanpak past.",
         actie="Vraag dakwerk aan",
         fotos=["dakwerk", "dak-1", "dak-plat", "dak-3"],
         blokken=[
             ("vergelijk", "Plat of schuin", "Het type dak bepaalt de vragen.",
              "Een plat dak en een pannendak hebben elk hun eigen aandachtspunten. Deze vragen helpen je om te beschrijven wat er speelt.",
              [("Plat dak", "Bij een plat dak draait het om de dakbedekking, de randen en hoe het water wegloopt.",
                ["Blijft er water staan na een regenbui?",
                 "Zie je blazen, scheuren of losse naden in de bedekking?",
                 "Hoe oud is de bedekking ongeveer?",
                 "Staat er iets op het dak, zoals zonnepanelen of een buitenunit?"]),
               ("Schuin dak", "Bij een schuin dak gaat het om de pannen, de constructie eronder en de aansluitingen.",
                ["Liggen er pannen los, verschoven of gebroken?",
                 "Zie je vocht of vlekken aan de binnenkant, op zolder?",
                 "Is het dak aan de binnenkant afgewerkt, of zie je de constructie nog?",
                 "Zitten er dakramen, een dakkapel of zonnepanelen in of op het dak?"])]),
             ("kaarten", "De aanpak", "Van gericht herstel tot een nieuw dak.",
              "Hoe ver het werk gaat, hangt af van wat we aantreffen. We bespreken eerlijk wat nodig is.",
              [("Herstellen wat kapot is", "Gaat het om één plek of één onderdeel, dan kijken we of gericht herstel volstaat en of de rest van het dak nog goed is."),
               ("Dakbedekking vernieuwen", "Is de bedekking van een plat dak op, dan bespreken we de vervanging en wat er onder de bedekking moet gebeuren."),
               ("Dak opnieuw opbouwen", "Moet het dak verder open, dan kan het in één keer opnieuw worden opgebouwd. Dat is ook het moment om isolatie mee te nemen.")]),
             ("tekst", "Eindhoven en omgeving", "Dakwerk aan een woning in de stad.",
              ["Bij een rijwoning of twee-onder-een-kapwoning loopt je dak door in dat van de buren. De aansluitingen en de overgang naar het buurdak verdienen dan extra aandacht. Het is ook handig als je buren weten dat er gewerkt gaat worden.",
               "In een drukke straat telt de bereikbaarheid mee: waar kan de steiger staan, is er ruimte voor materiaal en is een kraan nodig? Voor een steiger, container of kraan op de openbare weg is vaak toestemming van de gemeente nodig. Welke regels gelden, verschilt per gemeente.",
               "We werken vanuit Asten aan daken in Eindhoven, Helmond, Geldrop, Deurne, Someren en Asten zelf, en in de plaatsen daaromheen."]),
             ("info", "Je aanvraag", "Dit helpt ons om je dak te beoordelen.", "", [
                 "Plat of schuin dak, en bij benadering hoe groot",
                 "Wat je ziet of merkt: vocht, losse pannen, versleten bedekking",
                 "Sinds wanneer het speelt, als het om een probleem gaat",
                 "Foto's van het dak en van eventuele vochtplekken binnen",
                 "De postcode, zodat we weten waar het dak ligt en hoe het bereikbaar is"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.",
              "Een prijs vooraf noemen kan pas als we weten hoe jouw dak eraan toe is. Deze punten bepalen de kosten:", [
                 "De oppervlakte van het dak",
                 "Het type dak en wat er onder de pannen of de bedekking zit",
                 "Of het om een deel van het dak gaat of om het hele dak",
                 "De bereikbaarheid: hoogte, steiger en of er een kraan nodig is",
                 "Aansluitingen, dakramen en doorvoeren",
                 "Of isolatie in dezelfde ronde wordt meegenomen"]),
             ("combi", "Slim combineren", "Als het dak toch open gaat.", [
                 ("dakisolatie", "Moeten de pannen of de bedekking er toch af, dan ligt isoleren aan de buitenkant van het dak voor de hand."),
                 ("zolder", "Is het dak aan de binnenkant nog kaal, dan kan de zolder na het dakwerk worden geïsoleerd en afgewerkt.")]),
             ("vragen", "Vragen", "Vaak gesteld over dakwerk.", [
                 ("Moet ik weten wat er met mijn dak aan de hand is?", "Nee. Beschrijf wat je ziet of merkt. Waar het vandaan komt, zoeken we samen uit."),
                 ("Kan ook een deel van het dak worden aangepakt?", "Dat hangt af van de staat van de rest van het dak. Soms is gericht herstel genoeg, soms is het verstandiger een groter deel mee te nemen. Dat bespreken we vooraf."),
                 ("Ik heb zonnepanelen op mijn dak. Wat betekent dat?", "Zet het in je aanvraag. Panelen hebben invloed op de aanpak en de planning, omdat ze soms tijdelijk weg moeten om bij het dak te kunnen.")]),
         ]),

    dict(slug="dakisolatie", groep="dak", nr="02", naam="Dakisolatie", oppervlakte="dak",
         kort="Isolatie afgestemd op de opbouw van je dak en de ruimte eronder.",
         titel="Dakisolatie in Eindhoven en omgeving | Bouwpartners Eindhoven",
         meta="Je dak laten isoleren? We kijken naar de opbouw van je dak, hoe je de ruimte eronder gebruikt en welke afwerking erop komt. Bouwpartners Eindhoven, vanuit Asten.",
         h1="Dakisolatie in Eindhoven en omgeving",
         intro="Hoe je een dak het beste isoleert, hangt af van hoe het nu is opgebouwd en wat je met de ruimte eronder doet. Daar beginnen we mee.",
         actie="Vraag dakisolatie aan",
         fotos=["dak-1", "dak-2", "zolder-7"],
         blokken=[
             ("kaarten", "Waar het om draait", "Drie dingen bepalen de keuze.", "",
              [("Hoe het dak nu is opgebouwd", "Zit er al isolatie in, en zo ja hoeveel? Is het dak van binnen open of al afgewerkt? Weet je het niet, dan zoeken we het uit."),
               ("Wat je met de ruimte eronder doet", "Een zolder die je als slaapkamer of werkplek gebruikt, vraagt om een andere afwerking dan een bergzolder."),
               ("Hoe isolatie en afwerking aansluiten", "Isolatie werkt pas goed als de aansluitingen kloppen en vocht geen kans krijgt. Daarom stemmen we de isolatie af op de afwerking die erop komt.")]),
             ("vergelijk", "Binnen of buiten", "Twee manieren om een dak te isoleren.",
              "Welke manier past, hangt vooral af van de staat van het dak en wat je verder van plan bent.",
              [("Aan de buitenkant", "De isolatie komt op het dak, onder de pannen of de dakbedekking. Dat ligt voor de hand als het dak toch open moet.",
                ["Goed te combineren met vervanging van pannen of bedekking",
                 "De ruimte onder het dak blijft even groot",
                 "Het werk gebeurt buiten en hangt af van het weer"]),
               ("Aan de binnenkant", "De isolatie komt aan de binnenkant van het dak en wordt daarna afgewerkt. Dat ligt voor de hand als het dak zelf nog goed is.",
                ["Het dak zelf blijft dicht",
                 "Isoleren en afwerken van de zolder gaan samen op",
                 "Kost wat ruimte en stahoogte op zolder"])]),
             ("tekst", "Subsidie", "Subsidie voor dakisolatie.",
              ["Voor het isoleren van een dak of zolder bestaat de landelijke subsidie ISDE voor woningeigenaren. Of je ervoor in aanmerking komt, hangt af van de voorwaarden van RVO, zoals de isolatiewaarde en de oppervlakte. Volgens RVO vraag je de subsidie aan binnen 24 maanden nadat de werkzaamheden zijn afgerond.",
               'Bekijk de actuele voorwaarden op <a href="https://www.rvo.nl/subsidies-financiering/isde/woningeigenaren" rel="noopener" class="lnk">rvo.nl</a> voordat je een keuze maakt. Of je subsidie krijgt, beslist RVO.']),
             ("info", "Je aanvraag", "Wat we willen weten.", "", [
                 "Of het een schuin of plat dak is",
                 "Bij benadering de oppervlakte van het dak",
                 "Of er al isolatie in zit, als je dat weet",
                 "Hoe je de ruimte onder het dak gebruikt, of wilt gaan gebruiken",
                 "Of er aan het dak ook ander werk nodig is",
                 "Foto's van de binnenkant van het dak"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "De oppervlakte die geïsoleerd wordt",
                 "Isoleren aan de binnenkant of aan de buitenkant",
                 "De huidige opbouw en wat daarvan weg moet",
                 "De afwerking die op de isolatie komt",
                 "De bereikbaarheid van het dak of de zolder",
                 "Of het samen met ander dakwerk gebeurt"]),
             ("combi", "Slim combineren", "Isoleren hangt samen met de rest.", [
                 ("dakwerken", "Moet de bedekking of moeten de pannen er toch af, dan is isoleren aan de buitenkant in één keer mee te nemen."),
                 ("zolder", "Isoleer je aan de binnenkant, dan ligt het afwerken van de zolder in het verlengde.")]),
             ("vragen", "Vragen", "Vaak gesteld over dakisolatie.", [
                 ("Wat is beter: binnen of buiten isoleren?", "Dat hangt af van je dak. Moet het dak toch open, dan ligt buiten voor de hand. Is het dak goed en wil je de zolder afwerken, dan is binnen vaak logischer."),
                 ("Hoe weet ik of er al isolatie in mijn dak zit?", "Zie je op zolder de houten dakplaten of de onderkant van de pannen, dan is er aan de binnenkant in elk geval niets aangebracht. Is het dak al afgewerkt, dan is het lastiger te zien. Weet je het niet, zet dat dan in je aanvraag."),
                 ("Werken jullie ook in Eindhoven?", "Ja. Vanuit Asten werken we in Eindhoven, Helmond, Geldrop, Deurne, Someren en de plaatsen daaromheen.")]),
         ]),

    dict(slug="zolder", groep="dak", nr="03", naam="Zolder isoleren en afwerken", oppervlakte=None,
         kort="Van bergzolder naar slaapkamer, werkplek of nette bergruimte.",
         titel="Zolder isoleren en afwerken | Bouwpartners Eindhoven",
         meta="Van kale zolder naar slaapkamer, werkplek of nette bergruimte. We isoleren en werken je zolder af, afgestemd op hoe je de ruimte gaat gebruiken. Regio Eindhoven.",
         h1="Zolder isoleren en afwerken",
         intro="Een zolder wordt pas een echte kamer als hij goed geïsoleerd en netjes afgewerkt is. Wat er nodig is, begint bij één vraag: waar wil je de ruimte voor gebruiken?",
         actie="Vraag je zolder aan",
         fotos=["zolder-1", "zolder-2", "zolder-4", "zolder-6"],
         blokken=[
             ("kaarten", "De functie", "Wat wordt het?",
              "De functie bepaalt hoe ver de isolatie en de afwerking moeten gaan.",
              [("Slaapkamer", "Een kamer waar je slaapt, moet het hele jaar prettig zijn. Isolatie, ventilatie en daglicht verdienen dan extra aandacht."),
               ("Werkplek", "Voor thuiswerken tellen vooral de stahoogte, het daglicht en een prettige temperatuur."),
               ("Nette bergruimte", "Wil je de zolder vooral gebruiken om spullen kwijt te kunnen, dan kan de afwerking eenvoudiger."),
               ("Hobby- of speelruimte", "Een plek om te spelen of te sporten vraagt om een stevige vloer en een afwerking die tegen een stootje kan.")]),
             ("lijst", "Onderdelen", "Waaruit een zolderproject bestaat.",
              "Wat in jouw situatie nodig is, bespreken we vooraf. Dit zijn de onderdelen die in onze zolderprojecten terugkomen:", [
                 "Isolatie van het dak aan de binnenkant",
                 "Beplating van de schuine dakvlakken en de knieschotten",
                 "Een nieuwe of verstevigde vloer",
                 "Afwerking rond dakkapellen en dakramen",
                 "Een afgewerkt plafond, eventueel met inbouwspots"]),
             ("vergelijk", "Isoleren, afwerken of allebei", "Kies wat bij je plan past.", "",
              [("Alleen isoleren", "Je wilt vooral minder warmteverlies via het dak. De afwerking komt later, of de zolder blijft een bergruimte.",
                ["Het dak wordt aan de binnenkant geïsoleerd",
                 "Afwerken kan in een latere fase"]),
               ("Isoleren en afwerken", "Je wilt de zolder echt gaan gebruiken. Dan stemmen we isolatie en afwerking in één keer op elkaar af.",
                ["Eén keer de zolder leeg en één planning",
                 "De afwerking sluit direct aan op de isolatie"])]),
             ("info", "Je aanvraag", "Beschrijf je zolder.", "", [
                 "Hoe de zolder er nu uitziet: kaal, deels afgewerkt of al in gebruik",
                 "Waar je hem voor wilt gebruiken",
                 "Bij benadering de vloeroppervlakte en de hoogte onder de nok",
                 "Of er al dakramen of een dakkapel zijn",
                 "Hoe je de zolder bereikt: met een vaste trap of een vlizotrap",
                 "Foto's van de zolder"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "De oppervlakte van de zolder",
                 "Of isolatie wordt meegenomen",
                 "De staat van de vloer",
                 "Het aantal dakkapellen en dakramen dat moet worden afgewerkt",
                 "Het afwerkingsniveau dat je wilt",
                 "Hoe makkelijk materiaal naar boven kan"]),
             ("combi", "Slim combineren", "Eerst het dak, dan de zolder.", [
                 ("dakisolatie", "Lees meer over de keuze tussen isoleren aan de binnenkant en de buitenkant van het dak."),
                 ("dakwerken", "Is het dak zelf aan vervanging toe, pak dat dan eerst aan. Dan werk je de zolder daarna één keer goed af.")]),
             ("vragen", "Vragen", "Vaak gesteld over zolders.", [
                 ("Is mijn zolder hoog genoeg voor een kamer?", "Dat hangt af van de hoogte onder de nok en de helling van het dak. Geef de hoogte bij benadering door, dan kijken we wat er kan."),
                 ("Mijn zolder staat vol spullen. Is dat een probleem?", "Nee, maar voor het werk moet de zolder leeg zijn. Zet in je aanvraag hoe de zolder nu gebruikt wordt, dan houden we daar rekening mee in de planning.")]),
         ]),

    dict(slug="tuinaanleg", groep="tuin", nr="04", naam="Tuinaanleg", oppervlakte="tuin",
         kort="Een nieuwe tuin vanaf de basis, ook grotere projecten.",
         titel="Tuinaanleg in regio Eindhoven | Bouwpartners Eindhoven",
         meta="Een nieuwe tuin vanaf de basis: grondwerk, bestrating, gazon en beplanting. Bouwpartners Eindhoven uit Asten, in de regio en voor grote tuinen ook verder.",
         h1="Tuinaanleg in de regio Eindhoven",
         intro="Een nieuwe tuin begint bij wat er nu ligt: kale grond bij een nieuwbouwwoning, of een tuin die helemaal opnieuw moet. Van daaruit bespreken we de indeling en de materialen.",
         actie="Vraag tuinaanleg aan",
         fotos=["tuin-1", "tuin-5", "tuin-8", "tuin-3", "tuin-4"],
         blokken=[
             ("kaarten", "De beginsituatie", "Waar begin je?", "",
              [("Nieuwbouw", "Vaak ligt er alleen grond, soms met bouwresten of een slechte toplaag. Dan begint de tuin bij de ondergrond."),
               ("Een tuin die helemaal weg mag", "Alles eruit en opnieuw beginnen. Wat er nu ligt, moet eerst worden verwijderd."),
               ("Een grote tuin", "Bij een grote oppervlakte spelen hoogteverschillen, afwatering en de bereikbaarheid voor machines een grotere rol.")]),
             ("lijst", "Onderdelen", "Waaruit een nieuwe tuin bestaat.",
              "Welke onderdelen je kiest, bepaal je zelf. Deze komen in onze tuinprojecten terug:", [
                 "Grondwerk en egaliseren",
                 "Bestrating voor terras en paden",
                 "Gazon van graszoden of kunstgras",
                 "Borders, plantenbakken en beplanting",
                 "Een afscheiding, zoals een schutting of haag",
                 "Afwatering, zodat regenwater weg kan"]),
             ("tekst", "Grotere tuinprojecten", "Een grote tuin, ook buiten de regio.",
              ["Ons vaste werkgebied ligt rond Asten, Someren, Deurne, Helmond, Geldrop en Eindhoven. Voor de aanleg van een grotere tuin komen we ook verder. Of dat kan, hangt af van de locatie en de omvang van het werk.",
               "Zet je postcode en de geschatte oppervlakte in je aanvraag, dan laten we weten wat er mogelijk is."]),
             ("kaarten", "Keuzes", "Keuzes die de tuin bepalen.", "",
              [("Hoe je de tuin gebruikt", "Zitten, spelen, tuinieren of vooral weinig werk: dat bepaalt de verhouding tussen terras, gazon en beplanting."),
               ("Gras of bestrating", "Echt gras, kunstgras of meer bestrating vragen elk om een ander soort onderhoud."),
               ("Zon en schaduw", "Waar de zon staat, bepaalt waar je wilt zitten en wat er goed groeit.")]),
             ("info", "Je aanvraag", "Wat we willen weten.", "", [
                 "De postcode van de tuin",
                 "Bij benadering de oppervlakte",
                 "Wat er nu ligt",
                 "Hoe je de tuin wilt gebruiken",
                 "Een schets of ontwerp, als je dat hebt",
                 "Hoe de tuin bereikbaar is: via een achterom, een poort of alleen door het huis"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "De oppervlakte van de tuin",
                 "Het grondwerk en wat er moet worden afgevoerd",
                 "De bestrating en materialen die je kiest",
                 "Gras of kunstgras",
                 "De bereikbaarheid voor materiaal en machines",
                 "Extra onderdelen, zoals een schutting of overkapping"]),
             ("combi", "Slim combineren", "Alles in één ronde.", [
                 ("overkappingen-aanbouw", "Een overkapping en het terras eronder plan je het best samen met de rest van de tuin."),
                 ("bomen-verwijderen", "Staat er een boom op de plek van het nieuwe terras of gazon, dan kan die eerst weg.")]),
             ("vragen", "Vragen", "Vaak gesteld over tuinaanleg.", [
                 ("Heb ik een tuinontwerp nodig?", "Nee. Een schets, een paar voorbeeldfoto's of een beschrijving is genoeg om te beginnen. Heb je wel een ontwerp, stuur het dan mee."),
                 ("Wat is het verschil met tuinrenovatie?", 'Bij tuinaanleg begin je opnieuw. Bij een <a href="/tuinrenovatie" class="lnk">tuinrenovatie</a> verbeter je een bestaande tuin en blijft een deel staan.')]),
         ]),

    dict(slug="tuinrenovatie", groep="tuin", nr="05", naam="Tuinrenovatie", oppervlakte="tuin",
         kort="Je bestaande tuin vernieuwen: wat blijft en wat verandert.",
         titel="Tuinrenovatie in regio Eindhoven | Bouwpartners Eindhoven",
         meta="Je bestaande tuin vernieuwen: wat blijft er, wat verandert en waar hangt de prijs van af? Bouwpartners Eindhoven uit Asten, in de regio Eindhoven en verder.",
         h1="Tuinrenovatie: je bestaande tuin vernieuwen",
         intro="Bij een renovatie hoeft niet alles weg. We kijken samen wat goed is en blijft, en wat beter kan.",
         actie="Vraag tuinrenovatie aan",
         fotos=["tuin-2", "tuin-7", "tuin-10", "tuin-9", "tuin-6", "tuin-11"],
         blokken=[
             ("vergelijk", "Blijven of vernieuwen", "Wat blijft, wat verandert.",
              "Een renovatie begint met kijken naar wat er al ligt.",
              [("Wat vaak kan blijven", "Goede onderdelen houden, scheelt werk en geld.",
                ["Bomen en heesters die gezond zijn en op een goede plek staan",
                 "Een schutting of tuinhuis in goede staat",
                 "Bestrating die nog vlak ligt"]),
               ("Wat vaak aanleiding is", "Dit zijn de redenen waarom mensen hun tuin willen vernieuwen.",
                ["Verzakte of scheve bestrating",
                 "Een gazon dat er slecht bij ligt",
                 "Een indeling die niet meer past bij hoe je de tuin gebruikt",
                 "Water dat blijft staan na een bui"])]),
             ("kaarten", "De omvang", "Een hoek of de hele tuin.", "",
              [("Eén onderdeel", "Een nieuw terras, een ander pad of nieuw gazon. De rest van de tuin blijft zoals hij is."),
               ("Een deel van de tuin", "Bijvoorbeeld de voortuin, of de achtertuin vanaf het terras."),
               ("De hele indeling", 'Je houdt een paar dingen, maar de tuin krijgt een nieuwe opzet. Dan schuift het werk richting <a href="/tuinaanleg" class="lnk">tuinaanleg</a>.')]),
             ("tekst", "Hergebruik", "Hergebruiken waar het kan.",
              ["Bestaande tegels of klinkers kunnen soms opnieuw worden gelegd, bijvoorbeeld op een andere plek in de tuin. Of dat kan, hangt af van de staat van het materiaal en de nieuwe indeling.",
               "Zet in je aanvraag wat je graag wilt houden. Dan nemen we dat mee."]),
             ("info", "Je aanvraag", "Wat we willen weten.", "", [
                 "De postcode van de tuin",
                 "Bij benadering de oppervlakte",
                 "Wat je wilt houden en wat weg mag",
                 "Wat je nu stoort aan de tuin",
                 "Foto's van de huidige tuin"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "Hoeveel er weg moet en worden afgevoerd",
                 "Wat er kan worden hergebruikt",
                 "De oppervlakte die wordt vernieuwd",
                 "De materialen die je kiest",
                 "De bereikbaarheid van de tuin",
                 "Bomen of stronken die weg moeten"]),
             ("regio", "Werkgebied", "Ook voor grotere tuinen verder weg.",
              "Ons vaste werkgebied ligt rond Asten, Someren, Deurne, Helmond, Geldrop en Eindhoven. Voor een grotere tuinrenovatie komen we ook verder, afhankelijk van de locatie en de omvang van het werk."),
             ("combi", "Slim combineren", "Wat vaak samen gaat.", [
                 ("bomen-verwijderen", "Een boom die te groot is geworden of op de verkeerde plek staat, kan eerst weg."),
                 ("overkappingen-aanbouw", "Een renovatie is een goed moment om een overkapping boven het terras te plaatsen.")]),
             ("vragen", "Vragen", "Vaak gesteld over tuinrenovatie.", [
                 ("Kan de renovatie in fases?", "Dat kan soms, bijvoorbeeld eerst de achtertuin en later de voortuin. Zet het in je aanvraag, dan kijken we wat een logische volgorde is."),
                 ("Wat als ik nog niet weet wat ik wil?", "Beschrijf wat je stoort en hoe je de tuin wilt gebruiken. Dat is genoeg om te beginnen.")]),
         ]),

    dict(slug="bomen-verwijderen", groep="tuin", nr="06", naam="Bomen kappen en verwijderen", oppervlakte=None,
         kort="Een boom laten kappen, met oog voor de plek erna.",
         titel="Bomen kappen in regio Eindhoven | Bouwpartners Eindhoven",
         meta="Een boom laten kappen en verwijderen? Lees wat er speelt bij de boom, de standplaats, de vergunning en de plek erna. Bouwpartners Eindhoven, vanuit Asten.",
         h1="Bomen kappen en verwijderen",
         intro="Bij een boom die weg moet, spelen drie vragen: hoe groot is hij, waar staat hij en hoe kom je erbij? En wat moet er daarna met de plek gebeuren?",
         actie="Vraag het kappen aan",
         fotos=[],
         blokken=[
             ("kaarten", "De boom en de plek", "Drie dingen bepalen het werk.", "",
              [("De boom", "Soort, hoogte en stamdikte bij benadering. Een foto met iets ernaast voor de schaal helpt."),
               ("De standplaats", "Staat hij dicht bij het huis, een schutting, leidingen of de buren? Hoe minder ruimte eromheen, hoe meer de boom in delen naar beneden moet."),
               ("De bereikbaarheid", "Kom je via een achterom of poort in de tuin, of alleen door het huis? Dat bepaalt hoe materiaal en hout de tuin in en uit gaan.")]),
             ("lijst", "Na het kappen", "Wat er met de plek gebeurt.",
              "Bespreek vooraf wat je na het kappen wilt, zodat het werk daarop wordt afgestemd:", [
                 "Wat er met het hout moet gebeuren",
                 "Of de stronk eruit moet of mag blijven",
                 "Of de plek daarna opnieuw wordt ingericht, met gras, bestrating of een terras"]),
             ("tekst", "Vergunning en broedseizoen", "Eerst checken, dan kappen.",
              ['Of je een vergunning nodig hebt om een boom te kappen, bepaalt je gemeente. Dat hangt onder meer af van de plek en de dikte van de stam, en verschilt per gemeente. Doe bij twijfel de vergunningcheck in het <a href="https://omgevingswet.overheid.nl/" rel="noopener" class="lnk">Omgevingsloket</a> of vraag het na bij je gemeente.',
               "Vogels die broeden en hun nesten zijn beschermd. Zit er een bewoond nest in de boom, dan moet het kappen wachten. Houd daar rekening mee als je in het voorjaar of de zomer wilt laten kappen."]),
             ("info", "Je aanvraag", "Wat we willen weten.", "", [
                 "De postcode",
                 "Foto's van de boom en de plek waar hij staat",
                 "Hoogte en stamdikte bij benadering",
                 "Wat je na het kappen met de plek wilt",
                 "Of er al een vergunning is, als die nodig is"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "De grootte van de boom",
                 "De ruimte rond de boom en wat er dichtbij staat",
                 "De bereikbaarheid van de tuin",
                 "Wat er met het hout en de stronk moet gebeuren",
                 "Het aantal bomen"]),
             ("combi", "Slim combineren", "En dan de plek opnieuw inrichten.", [
                 ("tuinrenovatie", "Is de boom weg, dan kan de plek worden meegenomen in een vernieuwing van de tuin."),
                 ("tuinaanleg", "Gaat de hele tuin op de schop, dan hoort het kappen bij het begin van de aanleg.")]),
             ("vragen", "Vragen", "Vaak gesteld over bomen.", [
                 ("Ik weet niet welke boom het is. Is dat erg?", "Nee. Een foto van de boom, het blad en de stam is genoeg om mee te beginnen."),
                 ("Kunnen er meerdere bomen tegelijk weg?", "Ja, zet ze allemaal in je aanvraag. Dan bekijken we ze in één keer.")]),
         ]),

    dict(slug="overkappingen-aanbouw", groep="aanbouw", nr="07", naam="Overkappingen en aanbouwtjes", oppervlakte=None,
         kort="Beschut buiten zitten, of extra ruimte aan je huis.",
         titel="Overkapping of aanbouw laten bouwen | Bouwpartners Eindhoven",
         meta="Een houten overkapping om beschut buiten te zitten, of een aanbouwtje voor extra ruimte aan je huis. Bouwpartners Eindhoven bespreekt wat bij jouw plek past.",
         h1="Overkappingen en aanbouwtjes",
         intro="Een overkapping maakt je tuin bruikbaar bij zon en regen. Een aanbouwtje geeft je huis extra ruimte. Het verschil zit in hoe je de ruimte wilt gebruiken.",
         actie="Vraag je overkapping aan",
         fotos=["overkapping-1", "overkapping-9", "overkapping-6", "overkapping-3", "overkapping-8", "overkapping-7"],
         blokken=[
             ("vergelijk", "Overkapping of aanbouw", "Buiten zitten of binnen wonen.", "",
              [("Overkapping", "Een dak boven een terras, aan het huis of los in de tuin. De ruimte blijft buiten: open, of aan een of meer kanten dicht.",
                ["Beschut buiten zitten, koken of iets stallen",
                 "Op onze foto's: houten constructies met een plat dak",
                 "Wanden of glas zijn keuzes die je kunt bespreken"]),
               ("Aanbouwtje", "Een kleine uitbouw die bij het huis gaat horen, met dichte wanden en een dak. Je gebruikt de ruimte binnen.",
                ["Extra woonruimte, een bijkeuken of een berging",
                 "Vraagt om een fundering, isolatie en een goede aansluiting op het huis",
                 "De aansluiting op de gevel en het dak verdient extra aandacht"])]),
             ("kaarten", "Keuzes", "Wat je vooraf bedenkt.", "",
              [("Plek en maat", "Aan de gevel of los in de tuin, en hoe diep en breed. Meet het bij benadering uit."),
               ("Open of dicht", "Helemaal open, met één dichte wand tegen de wind, of rondom dicht."),
               ("Het dak", "Een dicht dak houdt de regen tegen. Hoe het water wordt afgevoerd, hoort bij het ontwerp."),
               ("Materiaal en uitstraling", "De overkappingen op onze foto's zijn van hout, naturel of geschilderd. Bespreek welke uitstraling je wilt.")]),
             ("tekst", "Vergunning", "Eerst de vergunningcheck.",
              ['Een overkapping of kleine aanbouw aan de achterkant van een woning is onder voorwaarden vergunningvrij. Of dat voor jouw plan geldt, hangt af van de plek, de maten en het omgevingsplan van je gemeente.',
               'Doe de vergunningcheck in het <a href="https://omgevingswet.overheid.nl/" rel="noopener" class="lnk">Omgevingsloket</a> voordat je opdracht geeft.']),
             ("info", "Je aanvraag", "Wat we willen weten.", "", [
                 "De postcode",
                 "Waar het moet komen: aan de gevel of los in de tuin",
                 "De afmetingen bij benadering",
                 "Waar je de ruimte voor wilt gebruiken",
                 "Foto's van de plek",
                 "Een tekening of voorbeeldfoto, als je die hebt"]),
             ("prijs", "Kosten", "Waar de prijs van afhangt.", "", [
                 "De afmetingen",
                 "Open, deels dicht of rondom dicht",
                 "Het dak en de afvoer van regenwater",
                 "De ondergrond en de fundering",
                 "Bij een aanbouw: isolatie, kozijnen en de aansluiting op het huis",
                 "Afwerking en materiaal"]),
             ("combi", "Slim combineren", "Samen met de tuin.", [
                 ("tuinaanleg", "Een nieuwe overkapping is een goed moment om het terras eronder en de tuin eromheen mee te nemen."),
                 ("tuinrenovatie", "Vernieuw je een deel van de tuin, dan sluit de overkapping er direct op aan.")]),
             ("vragen", "Vragen", "Vaak gesteld over overkappingen.", [
                 ("Heb ik een tekening nodig?", "Nee. Maten bij benadering, een foto van de plek en een idee van wat je wilt, zijn genoeg om te beginnen."),
                 ("Wat is het verschil tussen een overkapping en een aanbouw?", "Een overkapping is een dak boven een buitenruimte. Een aanbouw is een dichte ruimte die bij het huis gaat horen en die je binnen gebruikt.")]),
         ]),
]
D = {d["slug"]: d for d in DIENSTEN}

# Projecten op de homepage. Alleen wat op de foto te zien is; geen plaats of datum.
PROJECTEN = [
    dict(titel="Dak in opbouw", type="Dakwerken", foto="dak-1", dienst="dakwerken",
         tekst="Schuin dak tijdens het werk: dakplaten en panlatten liggen erop, de steiger staat er nog."),
    dict(titel="Zolder in afwerking", type="Zolder", foto="zolder-2", dienst="zolder",
         tekst="Beplating tegen de schuine dakvlakken, met een dakkapel en ramen in de kopgevel. Gefotografeerd tijdens het werk."),
    dict(titel="Houten overkapping", type="Overkapping", foto="overkapping-6", dienst="overkappingen-aanbouw",
         tekst="Overkapping met zitplek, terras en kunstgras."),
    dict(titel="Tuin met overkapping", type="Tuinaanleg", foto="tuin-1", dienst="tuinaanleg",
         tekst="Gazon, tegelpad en vuurschaal, met een overkapping met glazen wanden."),
]

# Fotogalerij op Ons werk: (filter, naam, dienst, foto's)
WERK = [("dak", "Dak", "dakwerken", ["dakwerk", "dak-1", "dak-plat", "dak-3", "dak-2"]),
        ("zolder", "Zolder", "zolder", ["zolder-1", "zolder-2", "zolder-3", "zolder-4", "zolder-5", "zolder-6", "zolder-7"]),
        ("tuin", "Tuin", "tuinaanleg", ["tuin-1", "tuin-4", "tuin-2", "tuin-9", "tuin-6", "tuin-8", "tuin-5", "tuin-3", "tuin-7", "tuin-10", "tuin-11", "tuin-12"]),
        ("overkapping", "Overkapping", "overkappingen-aanbouw", ["overkapping-1", "overkapping-3", "overkapping-6", "overkapping-4", "overkapping-2", "overkapping-9", "overkapping-5", "overkapping-7", "overkapping-8"])]

VRAGEN = [
    ("Waarvoor kan ik bij jullie terecht?", "Voor dakwerken, dakisolatie, het isoleren en afwerken van zolders, tuinaanleg, tuinrenovatie, het kappen en verwijderen van bomen, en overkappingen en aanbouwtjes."),
    ("In welke regio werken jullie?", "We zitten in Asten en werken in Asten, Someren, Deurne, Helmond, Geldrop, Eindhoven en de plaatsen daaromheen. Grotere projecten verder weg zijn bespreekbaar, vooral voor tuinaanleg en tuinrenovatie."),
    ("Mijn plannen zijn nog niet helemaal duidelijk. En nu?", "Beschrijf wat je wilt veranderen en waar je over twijfelt. Je hoeft nog geen uitgewerkt ontwerp te hebben om je plannen met ons te bespreken."),
    ("Kan ik meerdere werkzaamheden toelichten?", "Ja, zet de verschillende onderdelen in je bericht. Bijvoorbeeld je dak en zolder, of je tuin en een overkapping."),
    ("Wat kost mijn project?", "Dat hangt af van de omvang, de materialen en de situatie. Op elke dienstpagina lees je welke punten de prijs bepalen. Beschrijf je wensen, dan bespreken we de mogelijkheden en de kosten."),
]

AANPAK = [
    ("01", "Je vertelt wat er speelt", "Via het formulier, per mail of telefonisch. Een eerste idee is genoeg."),
    ("02", "We kijken wat er kan", "We bespreken de mogelijkheden, de aanpak en wat jij belangrijk vindt."),
    ("03", "Je weet waar je aan toe bent", "Pas als duidelijk is wat er gebeurt en wat het kost, gaan we aan de slag."),
]

# Schattingen in het formulier, altijd optioneel
OPPERVLAKTE = {
    "dak": ("Geschatte dakoppervlakte", ["Tot 30 m²", "30 tot 60 m²", "60 tot 100 m²", "Meer dan 100 m²", "Weet ik nog niet"]),
    "tuin": ("Geschatte tuinoppervlakte", ["Tot 50 m²", "50 tot 150 m²", "150 tot 300 m²", "Meer dan 300 m²", "Weet ik nog niet"]),
}
