GROEPEN = {"dak": "Dak & zolder", "tuin": "Tuin & bomen", "aanbouw": "Aanbouw"}

DIENSTEN = [
    dict(slug="dakwerken", groep="dak", nr="01", naam="Dakwerken", actie="Bespreek je dakwerk",
         h1="Je dak<br>aanpakken",
         kort="Je dak laten aanpakken.",
         intro="Heeft je dak aandacht nodig? Vertel ons wat er speelt, dan bespreken we wat er kan.",
         meta="Dakwerken in Eindhoven. Vertel Bouwpartners Eindhoven wat er met je dak aan de hand is en bespreek je project.",
         kop="Begin bij wat je ziet",
         punten=[("Wat is er met je dak?", "Beschrijf wat je ziet of wat je wilt laten doen. Een eerste indruk is genoeg."),
                 ("Wat voor dak is het?", "Schuin of plat, en bij benadering hoe groot. Dat helpt om het gesprek te beginnen."),
                 ("Wat wil je weten?", "Mogelijkheden, planning en kosten stemmen we af op jouw dak.")],
         fotos=[("dakwerk", "Vakman aan het werk op een dak in opbouw"), ("dak-1", "Schuin dak met isolatieplaten, steiger en kraan"),
                ("dak-plat", "Plat dak met nieuwe dakbedekking"), ("dak-3", "Woning in de steigers met een dak in opbouw")]),
    dict(slug="dakisolatie", groep="dak", nr="02", naam="Dakisolatie", actie="Bespreek je dakisolatie",
         h1="Je dak<br>isoleren",
         kort="Je dak laten isoleren.",
         intro="Wil je je dak laten isoleren? Bespreek met ons wat bij jouw dak past.",
         meta="Dakisolatie in Eindhoven. Bespreek met Bouwpartners Eindhoven wat bij jouw dak past.",
         kop="Elk dak is anders",
         punten=[("Hoe is je dak nu?", "Vertel wat je weet over de opbouw en de staat van je dak. Weet je het niet, dan is dat ook goed."),
                 ("Wat gebeurt er onder het dak?", "Gebruik je de zolder, of wil je dat gaan doen? Dan nemen we dat mee in het gesprek."),
                 ("Wat wil je weten?", "Welke aanpak past en wat die kost, hangt af van jouw dak. Dat stemmen we met je af.")],
         fotos=[("dak-1", "Schuin dak met isolatieplaten"), ("dak-2", "Isolatieplaten klaar om het dak op te gaan")]),
    dict(slug="zolder", groep="dak", nr="03", naam="Zolder isoleren en afwerken", actie="Bespreek je zolderplannen",
         h1="Meer doen met<br>je zolder",
         kort="Van kale zolder naar afgewerkte ruimte.",
         intro="Een zolder isoleren, afwerken of allebei. Vertel waar je de ruimte voor wilt gebruiken.",
         meta="Zolder isoleren en afwerken in Eindhoven. Bespreek je zolderplannen met Bouwpartners Eindhoven.",
         kop="De ruimte is er al",
         punten=[("Hoe ziet je zolder er nu uit?", "Kaal, deels afgewerkt of in gebruik als opslag. Beschrijf de huidige situatie."),
                 ("Waar wil je hem voor gebruiken?", "Een kamer, een werkplek of gewoon een nette ruimte. Jouw wens bepaalt de afwerking."),
                 ("Isoleren, afwerken of allebei?", "Laat weten wat je wilt laten doen, dan bespreken we hoe dat op elkaar aansluit.")],
         fotos=[("zolder-2", "Afgewerkte zolder met dakkapel en ramen"), ("zolder-1", "Afgewerkt schuin plafond met spots"),
                ("zolder-3", "Zolder met beplating rond de dakkapel"), ("zolder-5", "Zolder in opbouw met nieuwe vloer")]),
    dict(slug="tuinaanleg", groep="tuin", nr="04", naam="Tuinaanleg", actie="Bespreek je tuinplannen",
         h1="Een<br>nieuwe tuin",
         kort="Een nieuwe tuin laten aanleggen.",
         intro="Een tuin laten aanleggen? Vertel hoe je buiten wilt leven, dan bespreken we de indeling.",
         meta="Tuinaanleg in Eindhoven. Bespreek je tuinplannen met Bouwpartners Eindhoven.",
         kop="Buiten begint bij jouw plannen",
         punten=[("Hoe ligt de tuin er nu bij?", "Kale grond, een oude tuin of iets ertussenin. Beschrijf waar we mee beginnen."),
                 ("Hoe wil je de tuin gebruiken?", "Zitten, spelen, tuinieren of vooral weinig onderhoud. Dat bepaalt de indeling."),
                 ("Wat wil je weten?", "Mogelijkheden, planning en kosten stemmen we af op jouw tuin.")],
         fotos=[("tuin-1", "Tuin met gazon, staptegels en overdekte buitenruimte"), ("tuin-4", "Tuin met gazon, tegels en een houten schutting"),
                ("tuin-9", "Plantenbakken met split en olijfbomen"), ("tuin-6", "Tuinpad met grindstroken langs het gazon")]),
    dict(slug="tuinrenovatie", groep="tuin", nr="05", naam="Tuinrenovatie", actie="Bespreek je tuinplannen",
         h1="Je tuin<br>vernieuwen",
         kort="Je bestaande tuin laten vernieuwen.",
         intro="Is je tuin aan vernieuwing toe? Vertel wat je anders wilt en wat mag blijven.",
         meta="Tuinrenovatie in Eindhoven. Bespreek met Bouwpartners Eindhoven wat je aan je tuin wilt veranderen.",
         kop="Wat mag blijven, wat moet anders",
         punten=[("Wat stoort je nu?", "Beschrijf wat je anders wilt aan je tuin. Dat kan één hoek zijn of de hele indeling."),
                 ("Wat wil je houden?", "Laat weten wat goed is en mag blijven, dan nemen we dat mee."),
                 ("Wat wil je weten?", "Mogelijkheden, planning en kosten stemmen we af op jouw tuin.")],
         fotos=[("tuin-2", "Tuin met klinkerbestrating en verlichting"), ("tuin-7", "Staptegels in grind naast het gazon"),
                ("tuin-10", "Voortuin met split en plantenbakken"), ("tuin-12", "Gazon met haag")]),
    dict(slug="bomen-verwijderen", groep="tuin", nr="06", naam="Bomen kappen en verwijderen", actie="Bespreek je project",
         h1="Een boom<br>laten verwijderen",
         kort="Een boom laten weghalen.",
         intro="Staat er een boom die weg moet? Vertel ons om welke boom het gaat en waar hij staat.",
         meta="Bomen kappen en verwijderen in Eindhoven. Vertel Bouwpartners Eindhoven om welke boom het gaat.",
         kop="Eén boom, een paar vragen",
         punten=[("Om welke boom gaat het?", "Een indruk van de soort en de grootte helpt om het gesprek te beginnen."),
                 ("Waar staat hij?", "Dicht bij huis, bij de schutting of midden in de tuin. Beschrijf de plek."),
                 ("Wat wil je daarna?", "Wil je de plek opnieuw inrichten? Zet het erbij, dan bespreken we het samen.")],
         fotos=[]),
    dict(slug="overkappingen-aanbouw", groep="aanbouw", nr="07", naam="Overkappingen en aanbouwtjes", actie="Bespreek je overkapping of aanbouw",
         h1="Ruimte<br>erbij",
         kort="Een overdekte plek of extra ruimte aan huis.",
         intro="Beschut buiten zitten onder een overkapping, of extra ruimte aan huis met een aanbouwtje. Vertel hoe je die ruimte wilt gebruiken.",
         meta="Overkappingen en aanbouwtjes in Eindhoven. Bespreek je plannen met Bouwpartners Eindhoven.",
         kop="Maak ruimte voor meer thuis",
         punten=[("Waar moet het komen?", "Aan huis, los in de tuin of op een bestaand terras. Beschrijf de plek."),
                 ("Waar wil je de ruimte voor gebruiken?", "Buiten zitten, iets stallen of extra woonruimte. Dat bepaalt wat past."),
                 ("Wat wil je weten?", "Mogelijkheden, planning en kosten stemmen we af op jouw situatie.")],
         fotos=[("overkapping-1", "Houten overkapping aan de achterzijde van een woning"), ("overkapping-6", "Vrijstaande houten overkapping in de tuin"),
                ("overkapping-3", "Houten balkenconstructie van een overkapping"), ("overkapping-9", "Overkapping met terras en hangmat")]),
]
D = {d["slug"]: d for d in DIENSTEN}

# Hero: drie disciplines, elk met een eigen foto
HERO = {
    "dak": dict(foto="dakwerk", alt="Vakman aan het werk op een dak in opbouw", label="Werk op het dak",
                titel="Aandacht voor je dak.<br>Ruimte voor je plannen.",
                diensten="Dakwerken · Dakisolatie · Zolderafwerking", actie="Bespreek je dak of zolder", keuze="Dak & zolder"),
    "tuin": dict(foto="tuin-1", alt="Tuin met gazon, staptegels en overdekte buitenruimte", label="Tuin & buitenruimte",
                 titel="Buiten wordt een plek<br>om te blijven.",
                 diensten="Tuinaanleg · Tuinrenovatie · Bomen verwijderen", actie="Bespreek je tuinplannen", keuze="Tuin & bomen"),
    "aanbouw": dict(foto="overkapping-6", alt="Houten overkapping met zitgelegenheid in de tuin", label="Houten overkapping",
                    titel="Meer beschutting.<br>Meer buiten leven.",
                    diensten="Overkappingen · Aanbouwtjes", actie="Bespreek je overkapping", keuze="Aanbouw"),
}

# Projectoverzicht. De regio is het werkgebied van het bedrijf, niet het adres van een project.
PROJECTEN = [
    dict(nr="01", titel="Dak in opbouw", type="Dakwerk", regio="Regio Eindhoven",
         foto="dak-1", alt="Schuin dak met isolatieplaten, steiger en kraan",
         tekst="Dakvlak opnieuw opgebouwd met isolatie, panlatten en afwerking.", dienst="dakwerken"),
    dict(nr="02", titel="Zolder afgewerkt", type="Zolderafwerking", regio="Regio Eindhoven",
         foto="zolder-2", alt="Afgewerkte zolder met dakkapel en ramen",
         tekst="Van kale kap naar een afgewerkte ruimte met dakkapel en spots.", dienst="zolder"),
    dict(nr="03", titel="Houten overkapping", type="Overkapping", regio="Regio Eindhoven",
         foto="overkapping-6", alt="Vrijstaande houten overkapping in de tuin",
         tekst="Vrijstaande overkapping in hout, met terras en beplanting eromheen.", dienst="overkappingen-aanbouw"),
    dict(nr="04", titel="Tuin opnieuw aangelegd", type="Tuinaanleg", regio="Regio Eindhoven",
         foto="tuin-1", alt="Tuin met gazon, staptegels en overdekte buitenruimte",
         tekst="Nieuw gazon, staptegels en een overdekte plek om te zitten.", dienst="tuinaanleg"),
]

WERK = [("dak", "Dak", ["dakwerk", "dak-1", "dak-plat", "dak-3", "dak-2"]),
        ("zolder", "Zolder", ["zolder-2", "zolder-1", "zolder-3", "zolder-4", "zolder-5", "zolder-6", "zolder-7"]),
        ("tuin", "Tuin", ["tuin-1", "tuin-4", "tuin-2", "tuin-9", "tuin-6", "tuin-8", "tuin-5", "tuin-3", "tuin-7", "tuin-10", "tuin-11", "tuin-12"]),
        ("overkapping", "Overkapping", ["overkapping-1", "overkapping-3", "overkapping-6", "overkapping-4", "overkapping-2", "overkapping-9", "overkapping-5", "overkapping-7", "overkapping-8"])]

VRAGEN = [
    ("Waarvoor kan ik bij jullie terecht?", "Voor dakwerken, dakisolatie, zolderisolatie en afwerking, tuinaanleg, tuinrenovatie, bomen kappen en verwijderen, overkappingen en aanbouwtjes."),
    ("Mijn plannen zijn nog niet helemaal duidelijk. En nu?", "Beschrijf wat je wilt veranderen en waar je over twijfelt. Je hoeft nog geen uitgewerkt ontwerp te hebben om je plannen met ons te bespreken."),
    ("Kan ik meerdere werkzaamheden toelichten?", "Ja, zet de verschillende onderdelen in je bericht. Bijvoorbeeld je dak en zolder, of je tuin en een overkapping."),
    ("Wat kost mijn project?", "Dat hangt af van de omvang, materialen en de situatie. Beschrijf je wensen, zodat we de mogelijkheden en kosten kunnen bespreken."),
]

AANPAK = [
    ("01", "Je vertelt wat er speelt", "Via het formulier, per mail of telefonisch. Een eerste idee is genoeg."),
    ("02", "We kijken wat er kan", "We bespreken de mogelijkheden, de aanpak en wat jij belangrijk vindt."),
    ("03", "Je weet waar je aan toe bent", "Pas als duidelijk is wat er gebeurt en wat het kost, gaan we aan de slag."),
]

